version: '3.7'

services:
    kafka-ui:
      container_name: kafka-ui
      image: provectuslabs/kafka-ui:latest
      ports:
        - 8180:8080
      environment:
        # LOGGING_LEVEL_ROOT: TRACE
        KAFKA_CLUSTERS_0_NAME: aws
        KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: b-5.nonprodsitmsksasl.40je8c.c4.kafka.ap-southeast-1.amazonaws.com:9096
        KAFKA_CLUSTERS_0_SCHEMAREGISTRY: https://schema-registry-data.nonprod.galaxyfinx.in/apis/ccompat/v6
        KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_SSL
        KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: SCRAM-SHA-512
        KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="msk" password="21esQbdo5P0Gsseo";'
        DYNAMIC_CONFIG_ENABLED: "true"
      volumes:
        - ./role.yaml:/roles.yaml
    # registry:
    #   container_name: schema-registry
    #   image: quay.io/apicurio/apicurio-registry-kafkasql:2.4.0.Final
    #   ports:
    #     - "8081:8081"
    #   environment:
    #     QUARKUS_PROFILE: prod
    #     KAFKA_BOOTSTRAP_SERVERS: b-5.nonprodsitmsksasl.40je8c.c4.kafka.ap-southeast-1.amazonaws.com:9096
    #     REGISTRY_KAFKA_COMMON_SECURITY_PROTOCOL: SASL_SSL
    #     REGISTRY_KAFKA_COMMON_SASL_MECHANISM: SCRAM-SHA-512
    #     REGISTRY_KAFKA_COMMON_SASL_JAAS_CONFIG: org.apache.kafka.common.security.scram.ScramLoginModule required username="msk" password="21esQbdo5P0Gsseo";
    #     ENABLE_CCOMPAT_LEGACY_ID_MODE: "true"
    #     ENABLE_CCOMPAT_CANONICAL_HASH_MODE: "true"
    #     QUARKUS_HTTP_PORT: 8081
    # aws eks update-kubeconfig --region ap-southeast-1 --name non-prod-data-cluster
networks:
  default:
    external:
      name: sagemaker-local
